library("ggplot2")
library("reshape2")
data<-read.csv("C:/Users/David/Desktop/Plotting/HDLsamples.csv")
rownames(data)=make.names(data$Gene,unique=TRUE)
data<-data[,-1]
data<-t(data)
res<-cor(data)
dist<-sqrt(1-res^2)
row.order=hclust(dist(res))$order
col.order=rev(hclust(dist(res))$order)
res<-res[row.order,col.order]
resm<-melt(res)
q<-qplot(x=Var1,y=Var2,data=resm,fill=value,geom="tile")+
scale_fill_gradient2(limits=c(-1,1))+
theme(text=element_text(size=8),
axis.text.x=element_text(angle=90,hjust=1,vjust=0.5),
axis.title.x=element_blank(),axis.title.y=element_blank())
print(q)